spring.application.name=BackendJobPortal

#MySQL connectivity

spring.datasource.url=jdbc:mysql://localhost:3306/BackendJobPortal
spring.datasource.username=root
spring.datasource.password=saurabh12345

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hybernet config

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#email connectivity

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saurabhchakor949@gmail.com
spring.mail.password=ldwk bbin wkih dwiq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smpt.starttls.required=true


#Exception Messages

USER_FOUND= Email registered already.
USER_NOT_FOUND = User is not registered.
INVALID_CREDENTIALS= Invalid Credentials.
PROFILE_NOT_FOUND=Profile not found.

OTP_NOT_FOUND=OTP has been expired.
OTP_INCORRECT=OTP is incorrect.

JOB_NOT_FOUND=Job not found.
JOB_APPLIED_ALREADY=Already Applied to this Job.
APPLICANT_NOT_FOUND=Applicant not found.

